aws_region           = "us-east-1"
environment          = "qa"
project_name         = "myapp"
vpc_cidr             = "10.1.0.0/16"
public_subnet_cidr   = "10.1.1.0/24"
private_subnet_cidr  = "10.1.2.0/24"
instance_type        = "t2.small"
key_pair_name        = "my-key-pair"      # Change to your key pair
ssh_cidr             = "0.0.0.0/0"         # Change to your IP for security
enable_monitoring    = true
root_volume_size     = 25
